### PR TITLE
Modify the shape of the constant datasets

### PR DESCRIPTION
**Pull request by RemiLehe**
This shape used to be 1 instead of the actual number of particles.

@C0nsultant : Could you download this branch and check that the data works with your yt implementation (without manually changing the shape of the constant particle attributes). If it does, please click merge (assuming you have the proper permissions, otherwise let me know.)

### CODE REVIEW

**Comment by anokfireball** [comment]
For the moment I can only verify the 3D dataset (dimensionality in the 2D case does not fully work). If the shape in 2D (and I assume theta) is constructed the same way, this fixes the problem.

data00000500 h5_2d-profile_particle_position_relative_x_particle_position_relative_y_particle_weighting

**Comment by ax3l** [comment]
@C0nsultant btw, the image above looks quite wrong, we can take a look on Friday.

**Comment by ax3l** [comment]
@RemiLehe actually the picture is correct and your new 3D data set looks broken in the particle positions.
@C0nsultant will add an openPMD-viewer image in a few minutes.

**Comment by RemiLehe** [comment]
Ok. Should we have a phone conversation about it (see personal emails) ?

Btw, please remember that here (in the Warp simulation), the particle positions were initialized in a regularly-spaced manner (i.e. not randomly distributed). This is similar to what is done in Osiris for instance. 
Does that explain the features that seemed broken in the above picture?

**Comment by anokfireball** [comment]
For completenes, here is the plot (x/y on iteration 500) done with openPMD-viewer and a manual histogram from pyplot.
opmd-viewer
histo

**Comment by RemiLehe** [comment]
Both look okay to me (bearing in mind the above remark on the distribution of particles in Warp). What feature seemed broken to you @ax3l ?

**Pull request merged**
